name: dir

# Controls when the workflow will run
on: push
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
    
      - name: Checkout repo content
        uses: actions/checkout@v3
        
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
     
      - name: Execute Naming Convention Check
        #run: ls
        run: python directory.py
